### ISSUE TITLE
Fix UB

### ISSUE THREAD

**Issue by EllipticEllipsis** [decompals/ido-static-recomp#29]
Goal: get a whole project to compile with ASAN on

Currently known UB:
- [ ] `wrapper___ll_mul` will cause UB if multiplicands are too large (known to occur in `cfe`). Proposed solution: cast the multiplicands to unsigned first.
- [ ] `wrapper___ll_lshift` will cause UB if shift is too large (occurs in OoT `z_en_ossan.c`)

**Comment by hensldm** [comment]
Fixed in #31
