### ISSUE TITLE
Output Recomp Version

### ISSUE THREAD

**Issue by hensldm** [decompals/ido-static-recomp#45]
https://discord.com/channels/710646040331681844/1018032155877724210/1086453898979594270

tldr: should provide a way to tell which version of recomp a particular binary is. Perhaps just print version on `-v` option.

**Comment by EllipticEllipsis** [comment]
Being worked on on [this branch](https://github.com/decompals/ido-static-recomp/tree/versioning).
- [ ] Show program name
- [ ] Show OS used
- [ ] Show compiler used
- [ ] Show build date/time (In a sensible ISO format)
- [ ] Show git hash/tag/some summary thereof
- [ ] Integrate with Github actions/releases

**Comment by AngheloAlf** [comment]
Makefile can detect the OS used, so it could be set as a define there and passed to the build.c file when building it

**Comment by hensldm** [comment]
Closed by #61
